### ISSUE TITLE
Edits to storm events vignettes

### ISSUE THREAD

**Issue by theresekon** [geanders/noaastormevents#17]
Overview of noaastormevents typos: 
-Under map_events it reads "features of an events data" but should read "features of an event's data"
-in next paragraph, it reads "the package functions attempts" but should read "the package functions attempt" 

Details of noaastormevents typos: 
-does hurricane exposure data still only go until 2015? 
-under episodes versus events in fourth paragraph, it reads "one of the episode was a winter storm" but should read "one of the episodes.."
-under event locations, under step 3, it reads "The check the last two words" but should read "Then check.." 
-in paragraph under steps, it reads "In Wyoming, Park County was being match to a" but should read "Park County was being matched"

**Comment by egarpor** [comment]
Also, the final figure ("The following figure shows the top 50 episodes in terms of damages (property and crop damage combined) in 2015:") does not seem to be rendered.
