### ISSUE TITLE
Fix a warning for CRAN checks

### ISSUE THREAD

**Issue by geanders** [geanders/noaastormevents#28]
```
Undocumented arguments in documentation object 'process_input_args'
     ‘date_range’ ‘storm’
```

Let's see if we can figure this one out....

**Comment by theresekon** [comment]
Where is this issue arising again?

**Comment by geanders** [comment]
I think this showed up when we ran `check()`, somewhere in that long message output. It may be that it was something that cropped up downstream of the other problem that you fixed (https://github.com/geanders/noaastormevents/issues/26), though, in which case we might have already fixed it. Look through the output from `check` and see if you see this message anywhere in there now.

**Comment by geanders** [comment]
I think I've sorted this out in the latest commits. There was a place in the help documentation where we had `` #' #' `` two times in a row in one line, and I think that might have caused it.
